name: Testando Github Actions com Python
on: workflow_dispatch
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando repositório
        uses: actions/checkout@v3
      - name: Instalando Python em versão especifica
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalando requirements
        run: python script.py
      - name: Verificando a versão do Flask
        run: flask --version
  
